# you can override this using by setting a system property, for example -Des.logger.level=DEBUG
es.logger.level: INFO
rootLogger: ${es.logger.level}, file
logger:
  # log action execution errors for easier debugging
  action: DEBUG
  # reduce the logging for aws, too much is logged under the default INFO
  com.amazonaws: WARN
  index.indexing.slowlog: TRACE, slowlog_index
  index.search.slowlog: TRACE, slowlog_search

appender:
  file:
    type: file
    file: /var/log/elasticsearch.log
    layout:
      type: pattern
      conversionPattern: "timestamp=%d{ISO8601};severity=%p;category=%c;message=%m%n"

  slowlog_index:
    type: file
    file: /var/log/elasticsearch_slowlog_index.log
    layout:
      type: pattern
      conversionPattern: "timestamp=%d{ISO8601};severity=%p;category=%c;message=%m%n"

  slowlog_search:
    type: file
    file: /var/log/elasticsearch_slowlog_search.log
    layout:
      type: pattern
      conversionPattern: "timestamp=%d{ISO8601};severity=%p;category=%c;message=%m%n"
